//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjiznica
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.Posudenoes = new HashSet<Posudeno>();
            this.vracenoes = new HashSet<vraceno>();
        }
    
        public int bookID { get; set; }
        public string title { get; set; }
        public string authors { get; set; }
        public Nullable<double> average_rating { get; set; }
        public string isbn { get; set; }
        public string isbn13 { get; set; }
        public string language_code { get; set; }
        public Nullable<short> C__num_pages { get; set; }
        public Nullable<int> ratings_count { get; set; }
        public Nullable<int> text_reviews_count { get; set; }
        public Nullable<System.DateTime> publication_date { get; set; }
        public string publisher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posudeno> Posudenoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vraceno> vracenoes { get; set; }
    }
}
